services:
  - type: web
    name: django-design-trix
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4 