# Generated by Django 5.2.1 on 2025-06-07 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='token_created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='design',
            name='token_id',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='TokenMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=64, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('blockchain_verified', models.BooleanField(default=False)),
                ('hash_algorithm', models.CharField(default='SHA-256', max_length=20)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_metadata', to='core.design')),
            ],
        ),
    ]
